# Generated by Django 4.2 on 2023-07-07 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Primo',
            fields=[
                ('rol', models.IntegerField(primary_key=True, serialize=False)),
                ('mail', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('nick', models.CharField(max_length=100)),
                ('bussy_schedule', models.CharField(max_length=100)),
                ('desire_schedule', models.CharField(max_length=100)),
            ],
        ),
    ]
